### ISSUE TITLE
Rust crate publishing and versioning

### ISSUE THREAD

**Issue by szg251** [mlabs-haskell/lambda-buffers#178]
Publish `lbr-prelude` and `lbr-prelude-derive` to crates.io

# TODO
- [ ] bump version to v1
- [ ] configure CI to publish crates to crates.io on tag push
- [ ] if not to difficult, generate documentation to github pages (otherwise, using docs.rs is also sufficient)
- [ ] push a git tag
