### ISSUE TITLE
Codegen tasks

### ISSUE THREAD

**Issue by bladyjoker** [mlabs-haskell/lambda-buffers#46]
# Tasks
1. [ ]  Communicate with CTL team about extracting [CTL plutus-ledger-api types](https://github.com/Plutonomicon/cardano-transaction-lib/tree/develop/src/Internal/Plutus/Types) from CTL and into a separate library where we manage JSON/PlutusData/Eq (Otherwise we need to pull in the entire CTL -.-)
2. [x]  Deep dive into Haskell plutus-ledger-api and check what built in encodings we must reuse (PlutusData ofc, but JSON? Perhaps we need to write a JSON library for them),
3. [x] Plutarch type def generation from LB type defs, and how to implement Eq and PlutusData for these Plutarch types,
4. [x] Formulate a non-Plutus standard library of opaques, what goes in (numbers, text, string, list, arrays, set/maps etc)? Collect target types in target languages (Purescript, Haskell, Typescript and Rust in that order of priority)

**Comment by bladyjoker** [comment]
Stale
